### ISSUE TITLE
Possível bug nessa linha do código

### ISSUE THREAD

**Issue by odravison** [wirecardBrasil/moip-sdk-java#19]
https://github.com/wirecardBrasil/moip-sdk-java/blob/5bee84fa9457d7becfd18954bf5105037f49829c/src/main/java/br/com/moip/api/request/RequestMaker.java#L237

Pessoal, atentem para essa chamada que está tentando transformar um possível objeto Json.

Existem chamadas na API do MOIP que não retornam uma string json, como é o caso da chamada de verificação de conta existente. Onde as únicas repostas possíveis são: `200` ou `404` para indicar que existe ou não existe conta. Espero ter ajudado.

**Comment by odravison** [comment]
Esse bug é um grande problema quando o usuário tenta perguntar se a conta do WIRECARD existe. Vocês poderiam corrigir isso? Eu posso corrigir e contribuir se permitirem, mas não vou perder meu tempo sem saber se vocês vão aceitar o commit.

**Comment by somentelucas** [comment]
Oi @odravison, você tem razão, essa API de verificação de contas realmente não retorna JSON, portanto se ela passar por essa validação vai quebrar.

Se você puder abrir uma pull request pra gente com o fix ficaremos muito feliz em colocá-lo em um release de fix! Pode abrir sim que vai ajudar bastante! 😄
